# Generated by Django 5.2.1 on 2025-05-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_price_product_rating_product_sales_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
