# Generated by Django 5.2.8 on 2025-11-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_short_description_productfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            # Add slug field without unique constraint first so existing rows can be populated
            field=models.SlugField(blank=True, null=True, max_length=255),
        ),
    ]
