# Generated by Django 5.2.8 on 2025-11-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_populate_and_enforce_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscreenshot',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link when screenshot is clicked', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
