# Generated by Django 5.2.8 on 2025-11-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_productscreenshot_link_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='api.product'),
        ),
    ]
