# Generated by Django 5.2.8 on 2025-11-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_quoterequest_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscreenshot',
            name='title',
            field=models.CharField(blank=True, help_text='Screenshot title/description', max_length=200, null=True),
        ),
    ]
