# Generated by Django 5.2.8 on 2025-11-14 18:36

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'verbose_name': 'Product Quote', 'verbose_name_plural': 'Product Quotes'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Author name'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='img/no_image.jpg', help_text='Main image for the blog', upload_to='blogs/', verbose_name='Blog image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Blog slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Blog title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coursecategory', verbose_name='Course category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Live', 'Live'), ('Recorded', 'Recorded')], max_length=20, verbose_name='Course type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Enrollment deadline'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rich HTML description', null=True, verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(default='img/no_image.jpg', error_messages={'invalid': 'Upload a valid image file.'}, help_text='Main image for the course', upload_to='courses/', verbose_name='Course image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Instructor', max_length=100, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Bengali', 'Bengali'), ('Hindi', 'Hindi')], default='English', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Course price', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title if blank', max_length=255, unique=True, verbose_name='Course slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Students count'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for this course', to='api.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Course title', max_length=200, verbose_name='Course title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video ID for preview', null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(error_messages={'blank': 'Please provide a category name.', 'unique': 'A course category with this name already exists.'}, help_text='Unique name for this course category', max_length=100, unique=True, verbose_name='Course category name'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='total_courses',
            field=models.IntegerField(default=0, error_messages={'invalid': 'Enter a valid integer.'}, help_text='Number of courses under this category', verbose_name='Total courses'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='total_instructors',
            field=models.IntegerField(default=0, error_messages={'invalid': 'Enter a valid integer.'}, help_text='Number of instructors for this category', verbose_name='Total instructors'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='total_rating',
            field=models.FloatField(default=0, error_messages={'invalid': 'Enter a valid number.'}, help_text='Aggregated rating for this category', verbose_name='Total rating'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='total_reviews',
            field=models.IntegerField(default=0, error_messages={'invalid': 'Enter a valid integer.'}, help_text='Number of reviews collected for this category', verbose_name='Total reviews'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='total_students',
            field=models.IntegerField(default=0, error_messages={'invalid': 'Enter a valid integer.'}, help_text='Total enrolled students for this category', verbose_name='Total students'),
        ),
        migrations.AlterField(
            model_name='courseincludes',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='api.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='courseincludes',
            name='icon',
            field=models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('download', 'Download'), ('infinity', 'Lifetime Access'), ('mobile', 'Mobile Access'), ('trophy', 'Certificate')], default='video', max_length=20, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='courseincludes',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='courseincludes',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Included item'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='duration',
            field=models.CharField(help_text='e.g., 15:30', max_length=20, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='is_preview',
            field=models.BooleanField(default=False, verbose_name='Is preview'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Lesson title'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID', max_length=100, null=True, verbose_name='Video ID'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Registrant name'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='occupation',
            field=models.CharField(max_length=100, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Registration status'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='courserequirement',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='courserequirement',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Requirement'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='title',
            field=models.CharField(help_text='Title of this course section', max_length=200, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='coursewhatyoulearn',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='coursewhatyoulearn',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Learning outcome'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='contact_number',
            field=models.CharField(max_length=20, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Requester name'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicepackage', verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productcategory', verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='demo',
            field=models.URLField(blank=True, help_text='Optional demo URL', null=True, verbose_name='Demo URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Full product description (HTML allowed)', null=True, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, error_messages={'invalid': 'Enter a valid price.'}, help_text='Product price in the configured currency', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='img/no_image.jpg', error_messages={'invalid': 'Upload a valid image file.'}, help_text='Main image for the product. Defaults to a placeholder if not provided.', upload_to='products/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, error_messages={'invalid': 'Enter a valid rating.'}, help_text='Average rating (0-5)', max_digits=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, error_messages={'invalid': 'Enter a valid integer.'}, help_text='Number of completed sales', verbose_name='Sales count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short summary shown on listings', max_length=500, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly unique identifier (auto-generated from title if blank)', max_length=255, unique=True, verbose_name='Product slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Associated tags', to='api.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(error_messages={'blank': 'Please provide a product title.'}, help_text='Short, descriptive title for the product', max_length=200, verbose_name='Product title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(error_messages={'blank': 'Please provide a category name.', 'unique': 'A product category with this name already exists.'}, help_text='Unique name for this product category', max_length=100, unique=True, verbose_name='Product category name'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class or name', max_length=100, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name',
            field=models.CharField(error_messages={'blank': 'Feature name cannot be blank.'}, help_text='Short title of the product feature', max_length=100, verbose_name='Feature name'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productfeaturedimage',
            name='image',
            field=models.ImageField(default='img/no_image.jpg', error_messages={'invalid': 'Upload a valid image file.'}, help_text='Additional featured image for product', upload_to='products/featured/', verbose_name='Featured image'),
        ),
        migrations.AlterField(
            model_name='productfeaturedimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordering index for this featured image', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='productfeaturedimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_images', to='api.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productscreenshot',
            name='image',
            field=models.ImageField(default='img/no_image.jpg', error_messages={'invalid': 'Upload a valid image file.'}, help_text='Screenshot image for product', upload_to='products/screenshots/', verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='productscreenshot',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link when screenshot is clicked', null=True, verbose_name='Optional link'),
        ),
        migrations.AlterField(
            model_name='productscreenshot',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='productscreenshot',
            name='screen_type',
            field=models.CharField(choices=[('mobile', 'Mobile Screen'), ('desktop', 'Desktop Screen')], max_length=10, verbose_name='Screen type'),
        ),
        migrations.AlterField(
            model_name='productscreenshot',
            name='title',
            field=models.CharField(blank=True, help_text='Screenshot title/description', max_length=200, null=True, verbose_name='Screenshot title'),
        ),
        migrations.AlterField(
            model_name='producttechnology',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class or name', max_length=100, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='producttechnology',
            name='name',
            field=models.CharField(help_text='Name of technology used', max_length=100, verbose_name='Technology name'),
        ),
        migrations.AlterField(
            model_name='producttechnology',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='producttechnology',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='api.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='contact_number',
            field=models.CharField(max_length=20, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Requester name'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='api.product', verbose_name='Related product'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('quoted', 'Quoted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Quote status'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicecategory', verbose_name='Service category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_title',
            field=models.CharField(help_text='Short description of deliverable', max_length=255, verbose_name='Delivery title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='purchase_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Purchase number'),
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Title of the service', max_length=200, verbose_name='Service title'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(error_messages={'blank': 'Please provide a category name.', 'unique': 'A service category with this name already exists.'}, help_text='Unique name for this service category', max_length=100, unique=True, verbose_name='Service category name'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(default='img/no_image.jpg', error_messages={'invalid': 'Upload a valid image file.'}, help_text='Image for the service', upload_to='services/', verbose_name='Service image'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='api.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='contact_number',
            field=models.CharField(max_length=20, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='package_type',
            field=models.CharField(max_length=100, verbose_name='Package type'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_title',
            field=models.CharField(max_length=200, verbose_name='Service title'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='delivery_time',
            field=models.IntegerField(help_text='Delivery time in days', verbose_name='Delivery time (days)'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='description',
            field=models.TextField(verbose_name='Package description'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='package_type',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Basic', max_length=10, null=True, verbose_name='Package type'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='revision_count',
            field=models.IntegerField(verbose_name='Revision count'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='api.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(error_messages={'blank': 'Please provide a tag name.', 'unique': 'A tag with this name already exists.'}, help_text='Unique tag used to label products and courses', max_length=50, unique=True, verbose_name='Tag name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(verbose_name='Bio/description'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='personal_website',
            field=models.URLField(blank=True, verbose_name='Personal website'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profile_img',
            field=models.ImageField(default='img/no_image.jpg', error_messages={'invalid': 'Upload a valid image file.'}, help_text='Profile photo for the team member', upload_to='team/', verbose_name='Profile image'),
        ),
    ]
