# Generated by Django 5.2.6 on 2025-11-26 06:00

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name (auto-generated)', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 60 chars)', max_length=60, null=True, validators=[django.core.validators.MaxLengthValidator(60)])),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160, null=True, validators=[django.core.validators.MaxLengthValidator(160)])),
                ('og_image', models.ImageField(blank=True, help_text='Image for social media sharing (Open Graph)', null=True, upload_to='blogs/categories/og_images/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in category list')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='blog_blogca_slug_465e50_idx'), models.Index(fields=['is_active', 'display_order'], name='blog_blogca_is_acti_22f456_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name (auto-generated)', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 60 chars)', max_length=60, null=True, validators=[django.core.validators.MaxLengthValidator(60)])),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160, null=True, validators=[django.core.validators.MaxLengthValidator(160)])),
                ('og_image', models.ImageField(blank=True, help_text='Image for social media sharing', null=True, upload_to='blogs/subcategories/og_images/')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog SubCategory',
                'verbose_name_plural': 'Blog SubCategories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, help_text='Blog post title (max 200 chars)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly unique identifier (auto-generated from title)', max_length=250, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short description/summary (max 300 chars, used in listings)', max_length=300, null=True)),
                ('content', ckeditor.fields.RichTextField(help_text='Main blog post content (supports rich text)')),
                ('featured_image', models.ImageField(blank=True, help_text='Main featured image for the post', null=True, upload_to='blogs/featured/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (SEO)', max_length=125, null=True)),
                ('author_name', models.CharField(default='Admin', help_text='Display name for the author', max_length=100)),
                ('author_image', models.ImageField(blank=True, help_text='Author profile picture', null=True, upload_to='blogs/authors/')),
                ('author_bio', models.TextField(blank=True, help_text='Short author bio (max 500 chars)', max_length=500, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title for search engines (max 60 chars)', max_length=60, null=True, validators=[django.core.validators.MaxLengthValidator(60)])),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160, null=True, validators=[django.core.validators.MaxLengthValidator(160)])),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL (leave blank to auto-generate)', null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Custom image for social sharing (defaults to featured_image)', null=True, upload_to='blogs/og_images/')),
                ('og_title', models.CharField(blank=True, help_text='Custom title for social sharing (max 95 chars)', max_length=95, null=True)),
                ('og_description', models.CharField(blank=True, help_text='Custom description for social sharing (max 200 chars)', max_length=200, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text='Date and time to publish (for scheduling)', null=True)),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Total page views')),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('allow_indexing', models.BooleanField(default=True, help_text='Allow search engines to index this post')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Mark as featured post')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blog.blogcategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blog.blogsubcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogsubcategory',
            index=models.Index(fields=['slug'], name='blog_blogsu_slug_61a151_idx'),
        ),
        migrations.AddIndex(
            model_name='blogsubcategory',
            index=models.Index(fields=['category', 'is_active'], name='blog_blogsu_categor_dfdddf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blogsubcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-publish_date'], name='blog_blogpo_status_d8afa9_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', 'status'], name='blog_blogpo_categor_2e8dab_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', 'status'], name='blog_blogpo_is_feat_eb28c3_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-created_at'], name='blog_blogpo_created_2e77d7_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title'], name='blog_blogpo_title_2aa4d1_idx'),
        ),
    ]
